// Code generated by Kitex v0.9.1. DO NOT EDIT.

package miscservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	sc_misc_api "github.com/eyebluecn/sc-misc-idl/kitex_gen/sc_misc_api"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ColumnOmnibus": kitex.NewMethodInfo(
		columnOmnibusHandler,
		newMiscServiceColumnOmnibusArgs,
		newMiscServiceColumnOmnibusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RichColumnPage": kitex.NewMethodInfo(
		richColumnPageHandler,
		newMiscServiceRichColumnPageArgs,
		newMiscServiceRichColumnPageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ColumnQueryById": kitex.NewMethodInfo(
		columnQueryByIdHandler,
		newMiscServiceColumnQueryByIdArgs,
		newMiscServiceColumnQueryByIdResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"EditorLogin": kitex.NewMethodInfo(
		editorLoginHandler,
		newMiscServiceEditorLoginArgs,
		newMiscServiceEditorLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ReaderLogin": kitex.NewMethodInfo(
		readerLoginHandler,
		newMiscServiceReaderLoginArgs,
		newMiscServiceReaderLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ReaderQueryById": kitex.NewMethodInfo(
		readerQueryByIdHandler,
		newMiscServiceReaderQueryByIdArgs,
		newMiscServiceReaderQueryByIdResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"PaymentPaidCallback": kitex.NewMethodInfo(
		paymentPaidCallbackHandler,
		newMiscServicePaymentPaidCallbackArgs,
		newMiscServicePaymentPaidCallbackResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	miscServiceServiceInfo                = NewServiceInfo()
	miscServiceServiceInfoForClient       = NewServiceInfoForClient()
	miscServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return miscServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return miscServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return miscServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "MiscService"
	handlerType := (*sc_misc_api.MiscService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "sc_misc_api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func columnOmnibusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sc_misc_api.MiscServiceColumnOmnibusArgs)
	realResult := result.(*sc_misc_api.MiscServiceColumnOmnibusResult)
	success, err := handler.(sc_misc_api.MiscService).ColumnOmnibus(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMiscServiceColumnOmnibusArgs() interface{} {
	return sc_misc_api.NewMiscServiceColumnOmnibusArgs()
}

func newMiscServiceColumnOmnibusResult() interface{} {
	return sc_misc_api.NewMiscServiceColumnOmnibusResult()
}

func richColumnPageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sc_misc_api.MiscServiceRichColumnPageArgs)
	realResult := result.(*sc_misc_api.MiscServiceRichColumnPageResult)
	success, err := handler.(sc_misc_api.MiscService).RichColumnPage(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMiscServiceRichColumnPageArgs() interface{} {
	return sc_misc_api.NewMiscServiceRichColumnPageArgs()
}

func newMiscServiceRichColumnPageResult() interface{} {
	return sc_misc_api.NewMiscServiceRichColumnPageResult()
}

func columnQueryByIdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sc_misc_api.MiscServiceColumnQueryByIdArgs)
	realResult := result.(*sc_misc_api.MiscServiceColumnQueryByIdResult)
	success, err := handler.(sc_misc_api.MiscService).ColumnQueryById(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMiscServiceColumnQueryByIdArgs() interface{} {
	return sc_misc_api.NewMiscServiceColumnQueryByIdArgs()
}

func newMiscServiceColumnQueryByIdResult() interface{} {
	return sc_misc_api.NewMiscServiceColumnQueryByIdResult()
}

func editorLoginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sc_misc_api.MiscServiceEditorLoginArgs)
	realResult := result.(*sc_misc_api.MiscServiceEditorLoginResult)
	success, err := handler.(sc_misc_api.MiscService).EditorLogin(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMiscServiceEditorLoginArgs() interface{} {
	return sc_misc_api.NewMiscServiceEditorLoginArgs()
}

func newMiscServiceEditorLoginResult() interface{} {
	return sc_misc_api.NewMiscServiceEditorLoginResult()
}

func readerLoginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sc_misc_api.MiscServiceReaderLoginArgs)
	realResult := result.(*sc_misc_api.MiscServiceReaderLoginResult)
	success, err := handler.(sc_misc_api.MiscService).ReaderLogin(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMiscServiceReaderLoginArgs() interface{} {
	return sc_misc_api.NewMiscServiceReaderLoginArgs()
}

func newMiscServiceReaderLoginResult() interface{} {
	return sc_misc_api.NewMiscServiceReaderLoginResult()
}

func readerQueryByIdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sc_misc_api.MiscServiceReaderQueryByIdArgs)
	realResult := result.(*sc_misc_api.MiscServiceReaderQueryByIdResult)
	success, err := handler.(sc_misc_api.MiscService).ReaderQueryById(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMiscServiceReaderQueryByIdArgs() interface{} {
	return sc_misc_api.NewMiscServiceReaderQueryByIdArgs()
}

func newMiscServiceReaderQueryByIdResult() interface{} {
	return sc_misc_api.NewMiscServiceReaderQueryByIdResult()
}

func paymentPaidCallbackHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sc_misc_api.MiscServicePaymentPaidCallbackArgs)
	realResult := result.(*sc_misc_api.MiscServicePaymentPaidCallbackResult)
	success, err := handler.(sc_misc_api.MiscService).PaymentPaidCallback(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMiscServicePaymentPaidCallbackArgs() interface{} {
	return sc_misc_api.NewMiscServicePaymentPaidCallbackArgs()
}

func newMiscServicePaymentPaidCallbackResult() interface{} {
	return sc_misc_api.NewMiscServicePaymentPaidCallbackResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ColumnOmnibus(ctx context.Context, request *sc_misc_api.ColumnOmnibusRequest) (r *sc_misc_api.ColumnOmnibusResponse, err error) {
	var _args sc_misc_api.MiscServiceColumnOmnibusArgs
	_args.Request = request
	var _result sc_misc_api.MiscServiceColumnOmnibusResult
	if err = p.c.Call(ctx, "ColumnOmnibus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RichColumnPage(ctx context.Context, request *sc_misc_api.RichColumnPageRequest) (r *sc_misc_api.RichColumnPageResponse, err error) {
	var _args sc_misc_api.MiscServiceRichColumnPageArgs
	_args.Request = request
	var _result sc_misc_api.MiscServiceRichColumnPageResult
	if err = p.c.Call(ctx, "RichColumnPage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ColumnQueryById(ctx context.Context, request *sc_misc_api.ColumnQueryByIdRequest) (r *sc_misc_api.ColumnQueryByIdResponse, err error) {
	var _args sc_misc_api.MiscServiceColumnQueryByIdArgs
	_args.Request = request
	var _result sc_misc_api.MiscServiceColumnQueryByIdResult
	if err = p.c.Call(ctx, "ColumnQueryById", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) EditorLogin(ctx context.Context, request *sc_misc_api.EditorLoginRequest) (r *sc_misc_api.EditorLoginResponse, err error) {
	var _args sc_misc_api.MiscServiceEditorLoginArgs
	_args.Request = request
	var _result sc_misc_api.MiscServiceEditorLoginResult
	if err = p.c.Call(ctx, "EditorLogin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReaderLogin(ctx context.Context, request *sc_misc_api.ReaderLoginRequest) (r *sc_misc_api.ReaderLoginResponse, err error) {
	var _args sc_misc_api.MiscServiceReaderLoginArgs
	_args.Request = request
	var _result sc_misc_api.MiscServiceReaderLoginResult
	if err = p.c.Call(ctx, "ReaderLogin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReaderQueryById(ctx context.Context, request *sc_misc_api.ReaderQueryByIdRequest) (r *sc_misc_api.ReaderQueryByIdResponse, err error) {
	var _args sc_misc_api.MiscServiceReaderQueryByIdArgs
	_args.Request = request
	var _result sc_misc_api.MiscServiceReaderQueryByIdResult
	if err = p.c.Call(ctx, "ReaderQueryById", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PaymentPaidCallback(ctx context.Context, request *sc_misc_api.PaymentPaidCallbackRequest) (r *sc_misc_api.PaymentPaidCallbackResponse, err error) {
	var _args sc_misc_api.MiscServicePaymentPaidCallbackArgs
	_args.Request = request
	var _result sc_misc_api.MiscServicePaymentPaidCallbackResult
	if err = p.c.Call(ctx, "PaymentPaidCallback", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
